# Generated by Django 3.1.6 on 2021-02-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermail',
            name='last_read_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
