# Generated by Django 3.1.6 on 2021-03-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mails', '0002_usermail_last_read_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermail',
            old_name='mail_sent_at',
            new_name='sent_at',
        ),
    ]
